# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_submissiondate', models.DateField()),
                ('assignment_description', models.CharField(default='Midsem feedback', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.IntegerField()),
                ('Course_slot', models.IntegerField()),
                ('Course_name', models.CharField(max_length=200)),
                ('Course_Sem', models.CharField(choices=[('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=10)),
                ('Course_MidSemDate', models.DateField()),
                ('Course_EndSemDate', models.DateField()),
                ('Course_Instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(choices=[('MidSem', 'MidSem'), ('EndSem', 'EndSem')], max_length=200)),
                ('feedback_submissiondate', models.DateField()),
                ('feedback_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlogin.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlogin.FeedbackAns')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlogin.FeedbackQuestions'),
        ),
        migrations.AddField(
            model_name='course',
            name='Course_students',
            field=models.ManyToManyField(to='adminlogin.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlogin.Course'),
        ),
    ]
